version: "3.9"

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: gisgraphy-image
    container_name: gisgraphy
    depends_on:
      - "database"
    ports:
      - 8080:8080
    environment:
      PG_USER: mdppostgres
      PG_PASS: pgsecurepass
      PG_HOST: database
      GISGRAPHY_DB: gisgraphy

  database:
    image: postgres:14.1-alpine
    container_name: postgres-db
    restart: always
    command: postgres -c password_encryption=md5
    environment:
      POSTGRES_USER: mdppostgres
      POSTGRES_PASSWORD: pgsecurepass